# Generated by Django 5.1.1 on 2026-01-07 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elderly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(help_text='전주 지역구 포함', max_length=255)),
                ('emergency_contact', models.CharField(max_length=100)),
                ('baseline', models.JSONField(blank=True, default=dict)),
                ('learning_progress', models.PositiveSmallIntegerField(default=0, help_text='0~100 진행률')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('RED', 'RED'), ('YELLOW', 'YELLOW')], max_length=10)),
                ('risk_type', models.CharField(help_text='낙상 등 위험 내용', max_length=100)),
                ('handled', models.BooleanField(default=False)),
                ('skeleton_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dashboard.elderly')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_score', models.FloatField()),
                ('activity_level', models.FloatField()),
                ('environment', models.JSONField(blank=True, default=dict, help_text='온습도 등 환경 데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='dashboard.elderly')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_completed', models.BooleanField(default=False)),
                ('badge_image', models.CharField(blank=True, help_text='배지 이미지 경로 또는 URL', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elderly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quests', to='dashboard.elderly')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
