# Generated by Django 5.2.10 on 2026-01-08 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_environmentreading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('emotion', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='dashboard.elderly')),
            ],
        ),
        migrations.CreateModel(
            name='ElderlyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_pose', models.JSONField(blank=True, default=dict)),
                ('baseline_face', models.JSONField(blank=True, default=dict)),
                ('mood_score', models.FloatField(default=0.0)),
                ('safety_state', models.CharField(default='normal', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='dashboard.elderly')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=16)),
                ('reason', models.CharField(max_length=200)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elderly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_alerts', to='dashboard.elderly')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
