# Generated by Django 5.2.10 on 2026-01-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_conversation_elderlystatus_emergencyalert'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentGuideLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('message', models.TextField()),
                ('reason', models.CharField(blank=True, max_length=32)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environment_guides', to='dashboard.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
